language: csharp
sudo: required
dotnet: 2.1.300
solution: RSOILab1.sln
dist: trusty  
mono: none

before_script:
  - dotnet restore
script:  
  dotnet build RSOILab1.sln -c Release


deploy: 
  provider: heroku
  buildpack: eric/dotnetcore-with-migration-newrelic
  api_key: 1d8e023e-2cc2-4ebe-a800-203bc102b8e3
  app: rsoilab