language: csharp
sudo: required
dotnet: 2.1.300
solution: RSOILab1.sln
dist: trusty  
mono: none

before_script:
  - dotnet restore
script:  
  dotnet build RSOILab1.sln -c Release


deploy:
  provider: heroku
  buildpack: http://github.com/noliar/dotnet-buildpack.git
  api_key: 
    secure: $HEROKU_AUTH_TOKEN
  app: rsoilab